@startuml inline_umlgraph_1.png
skinparam SequenceMessageAlign center
!pragma teoz true

title WNM Sleep Overview

box Station Side
participant APP
participant MMWLAN
participant CHIP
end box

box Access Point
participant AP
end box

== STA has already associated to the AP ==
== Enable WNM sleep ==

APP -> MMWLAN: mmwlan_set_wnm_sleep_enabled(true) \n mmwlan_set_wnm_sleep_enabled_ext(&wnm_sleep_args)

loop Retry until succesful response, error, or max attempts (60)
    MMWLAN -> AP: \t\t\t tx_wnm_action_frame (req) \t\t
    ... sometime later (~100ms in most cases) ...
    AP -> MMWLAN: \t\t\t tx_wnm_action_frame (resp) \t\t
end

alt successful response from AP
    alt Chip Power Down=True
        MMWLAN -> CHIP: Power down chip
        CHIP --> MMWLAN
    else Chip Power Down=False
        MMWLAN -> CHIP: Enter low power mode
        CHIP --> MMWLAN
    end

    MMWLAN --> APP: MMWLAN_SUCCESS
    else #Pink Exceeded retry attempts
    MMWLAN --> APP: MMWLAN_TIMED_OUT
    else #LightCoral Some other error
    MMWLAN --> APP: MMWLAN_ERROR
end

== Disable WNM sleep ==

APP -> MMWLAN: mmwlan_set_wnm_sleep_enabled(false) \n mmwlan_set_wnm_sleep_enabled_ext(&wnm_sleep_args)

alt Chip Power Down=True
    MMWLAN -> CHIP: Power up chip
    CHIP --> MMWLAN
else Chip Power Down=False
    MMWLAN -> CHIP: Exit low power mode
    CHIP --> MMWLAN
end

loop Retry until succesful response, error, or max attempts (60)
    MMWLAN -> AP: \t\t\t tx_wnm_action_frame (req) \t\t
    ... sometime later (~100ms in most cases) ...
    AP -> MMWLAN: \t\t\t tx_wnm_action_frame (resp) \t\t
end

alt successful response from AP
    MMWLAN --> APP: MMWLAN_SUCCESS
    else #Pink Exceeded retry attempts
    MMWLAN --> APP: MMWLAN_TIMED_OUT
    else #LightCoral Some other error
    MMWLAN --> APP: MMWLAN_ERROR
end
@enduml
